Fix incremental builds
Some recent CLs changed the list of files that are installed in the
root directory.  Incremental builds have no way to uninstall files
that were previously installed, which results in old stray files lying
around.  If the root directory is contained in system.img, this causes
an error while building system.img:
error: build_directory_structure: cannot lookup security context for /service_contexts

Update CleanSpec.mk to remove files obsoleted by:
Ide67d37d85273c60b9e387e72fbeb87be6da306a
I7881af8922834dc69b37dae3b06d921e05206564
Ide67d37d85273c60b9e387e72fbeb87be6da306a

This is not seen on the incremental build servers because they run
make installclean between builds.

Test: incremental build passes
Change-Id: I22ecd1d3698404df352263fa99b56cb65247a23b